# Generated by Django 5.0.2 on 2024-03-07 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='model_auto',
            new_name='model',
        ),
    ]
